use tdba;
insert into IssueList (JsonData)
  VALUES ('{  
         "expand":"operations,versionedRepresentations,editmeta,changelog,renderedFields",
         "id":"433432",
         "self":"https://jira.cso-hp.com/rest/api/2/issue/433432",
         "key":"QXWSOL-29",
         "fields":{  
            "summary":"Transfer ownership of mempool.vcs.rd.hpicorp.net",
            "description":"Tam had originally set this up, but he is recommending this tool be dismantled.  I am adding this story to ensure no tools neglected, even those recommended for decommission.\r\n\r\nHere is the email thread:\r\n\r\n=====================================\r\n\r\nDan:\r\n\r\nI am okay with decommissioning the server.  I do not for see us using this.\r\n\r\nRegards,\r\n\r\nTam\r\n\r\n \r\n\r\n*From:* Mehl, Cameron (FWQE) \r\n*Sent:* Monday, November 06, 2017 10:00 AM\r\n*To:* Ross, Eric P (QxE FW & Solution Quality) <[eric.ross@hp.com|mailto:eric.ross@hp.com]>; Crossman, Dan (VCS R&D IT) <[dan.crossman@hp.com|mailto:dan.crossman@hp.com]>; Pham, Tam T <[tam.t.pham@hp.com|mailto:tam.t.pham@hp.com]>\r\n*Cc:* Fritz, Terry M <[terry.fritz@hp.com|mailto:terry.fritz@hp.com]>\r\n*Subject:* RE: mempool update\r\n\r\n \r\n\r\nAdding in Tam as he originally wrote tools to leverage mapping it; there has been no transition setup for this yet so it is in a bit of a limbo while we figure out where it lands.\r\n\r\n[@Pham, Tam T|mailto:tam.t.pham@hp.com]: Was this a server that you had owned at one point? Since R&D will own it, I want to check in and determine if an upgrade is ok for it. If you don’t own it, then please let me know so Terry and I can figure out where it should land and who should own it.\r\n\r\nCameron\r\n\r\n \r\n\r\n*From:* Ross, Eric P (QxE FW & Solution Quality) \r\n*Sent:* Monday, November 6, 2017 9:44 AM\r\n*To:* Crossman, Dan (VCS R&D IT) <[dan.crossman@hp.com|mailto:dan.crossman@hp.com]>\r\n*Cc:* Fritz, Terry M <[terry.fritz@hp.com|mailto:terry.fritz@hp.com]>; Mehl, Cameron (FWQE) <[cameron.mehl@hp.com|mailto:cameron.mehl@hp.com]>\r\n*Subject:* Re: mempool update\r\n\r\n \r\n\r\nI don''t own this anymore as it has been transferred to R&D.  Please contact Cameron and/or Terry.\r\n\r\n \r\n\r\n*Eric Ross*\r\nAnalytics and Automation Architect\r\n\r\nQxE FW & Solution Quality\r\n\r\n \r\n\r\nEric Ross <[eric.ross@hp.com|mailto:eric.ross@hp.com]>\r\n\r\nPC Phone 1.360.212.9001\r\nHewlett-Packard Company\r\nVancouver, WA 98683\r\nUnited States\r\n\r\n \r\n\r\n*From:* Dan Crossman <[dan.crossman@hp.com|mailto:dan.crossman@hp.com]>\r\n*Date:* Monday, November 6, 2017 at 9:17 AM\r\n*To:* \"Ross, Eric P (QxE FW & Solution Quality)\" <[eric.ross@hp.com|mailto:eric.ross@hp.com]>\r\n*Subject:* mempool update\r\n\r\n \r\n\r\nHi Eric - Roger’s asking to get mempool.vcs.rd.hpicorp.net upgraded to Ubuntu 14 asap.   Ubuntu 12 is getting flagged as insecure.\r\n\r\nHow would you like to proceed?   I’m happy to take it.\r\n\r\n \r\n\r\n-dan\r\n\r\n ",
         }
      }');